# Supabase のプロジェクトURL
SUPABASE_URL = "https://lwemgiikifsdtgmbumkx.supabase.co"

# Supabase の anon public key
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZW1naWlraWZzZHRnbWJ1bWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNTA3MDYsImV4cCI6MjA4NDcyNjcwNn0.qrW-LLC858vPOqSG6tS5QrIr4je-2uhyM1ZkI6CFl50"
